/**
 * Database row shapes, mirroring `supabase/migrations/`.
 *
 * Hand-written rather than generated by the Supabase CLI. The CLI needs a live
 * project or a local Docker stack to introspect, which would make `typecheck`
 * depend on infrastructure being up — a CI job should not need a database to
 * find out whether the code compiles.
 *
 * The cost is that this file must be edited alongside any migration. The
 * repository mappers are the enforcement point: a column renamed in SQL but
 * not here produces a type error the moment a mapper reads it.
 */

export type ProfileRow = {
  id: string;
  name: string;
  headline: string;
  summary: string;
  bio: string[];
  avatar_url: string | null;
  location: string;
  website_url: string | null;
  email: string;
  resume_url: string | null;
  availability_status: "open" | "selective" | "unavailable";
  availability_label: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};

export type TechnologyRow = {
  id: string;
  name: string;
  category:
    | "languages"
    | "frameworks"
    | "backend"
    | "database"
    | "devops"
    | "cloud"
    | "tools"
    | "other";
  icon: string | null;
  is_primary: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
};

export type ProjectRow = {
  id: string;
  slug: string;
  title: string;
  description: string;
  overview: string[];
  highlights: string[];
  image_url: string | null;
  github_url: string | null;
  gitlab_url: string | null;
  live_url: string | null;
  featured: boolean;
  type: "web-app" | "api" | "library" | "tool" | "data" | "mobile";
  status: "shipped" | "in-progress" | "archived" | "concept";
  start_date: string;
  end_date: string | null;
  primary_language: string | null;
  sort_order: number;
  created_at: string;
  updated_at: string;
};

export type ProjectTechnologyRow = {
  project_id: string;
  technology_id: string;
  sort_order: number;
};

/**
 * A project joined with its technologies.
 *
 * PostgREST returns an embedded resource as a nested array when selected as
 * `project_technologies ( technology_id, sort_order )`.
 */
export type ProjectWithTechnologiesRow = ProjectRow & {
  project_technologies: Pick<
    ProjectTechnologyRow,
    "technology_id" | "sort_order"
  >[];
};

export type ExperienceRow = {
  id: string;
  title: string;
  company: string;
  company_url: string | null;
  location: string | null;
  kind: "work" | "education" | "project" | "volunteer";
  description: string;
  achievements: string[];
  technologies: string[];
  start_date: string;
  end_date: string | null;
  is_current: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
};

export type SocialLinkRow = {
  id: string;
  platform: "github" | "gitlab" | "linkedin" | "email" | "spotify" | "x";
  label: string;
  url: string;
  handle: string | null;
  sort_order: number;
  is_visible: boolean;
  created_at: string;
  updated_at: string;
};

export type PortfolioSettingRow = {
  key: string;
  value: unknown;
  description: string | null;
  updated_at: string;
};

/**
 * The shape `createClient<Database>()` expects. Only `Row` is filled in:
 * writes go through the service role in scripts and admin tooling, not
 * through typed inserts in application code.
 */
export type Database = {
  public: {
    Tables: {
      profiles: { Row: ProfileRow };
      technologies: { Row: TechnologyRow };
      projects: { Row: ProjectRow };
      project_technologies: { Row: ProjectTechnologyRow };
      experiences: { Row: ExperienceRow };
      social_links: { Row: SocialLinkRow };
      portfolio_settings: { Row: PortfolioSettingRow };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
